# Generated by Django 4.2.4 on 2023-09-22 10:05

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kategori',
            name='children',
        ),
        migrations.AddField(
            model_name='kategori',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='kurs.kategori'),
        ),
    ]
