# Generated by Django 4.2.4 on 2023-09-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0004_kurs_is_web'),
    ]

    operations = [
        migrations.AddField(
            model_name='kurs',
            name='is_program',
            field=models.BooleanField(default=False),
        ),
    ]
